apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-kubernetes-inform
  labels:
    app: quarkus-kubernetes-inform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus-kubernetes-inform
  template:
    metadata:
      labels:
        app: quarkus-kubernetes-inform
    spec:
      serviceAccountName: cos-fleetshard-sync
      containers:
      - env:
        - name: WATCH_MODE
          value: inform
        - name: WATCH_NAMESPACE
          value: redhat-openshift-connectors-caor78j7orh5vio9aa40
        image: quay.io/lburgazzoli/quarkus-k8s-watch:latest
        imagePullPolicy: Always
        name: quarkus-kubernetes-inform